sonar.projectKey=com.gridpulse:gridpulse
sonar.projectName=GridPulse
sonar.projectVersion=1.0.0

sonar.sources=backend/src/main,frontend/src
sonar.tests=backend/src/test
sonar.java.binaries=backend/target/classes

sonar.exclusions=**/node_modules/**,**/dist/**,**/target/**,**/build-war.*,**/*.spec.*,**/*.test.*,frontend/tailwind.config.js,frontend/postcss.config.js

sonar.sourceEncoding=UTF-8
